version:       1.0.{build}
image:         WMF 5

build_script:
  - ps:        'powershell-helpers/generateAllPackages.ps1'

artifacts:
  - path:      '**\*.nupkg'
    name:      nupkg
  - path:      '**\*.nuspec'
    name:      nuspec
  - path:      '**\.version'
    name:      version
  - path:      '.\**'
    name:      everything
